"use client";

import { FormEvent, useEffect, useState } from "react";
const apiBaseUrl = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:4000/api";
type Kind = "analytics" | "notifications" | "clubs" | "library";
type RecordItem = Record<string, unknown> & { id?: string; title?: string; status?: string; startsAt?: string };
const metricLabels: Record<string, string> = { users: "Ученики", activeUsers30d: "Активны за 30 дней", activeUsers7d: "Активны за 7 дней", retention7to30: "Удержание, %", lessonCompletions30d: "Уроков завершено", taskAttempts30d: "Попыток заданий", averagePoints: "Средний балл", upcomingClubs: "Ближайшие клубы", campaigns: "Кампании" };

export function AdminExperienceWorkspace({ kind }: { kind: Kind }) {
  const [items, setItems] = useState<RecordItem[]>([]); const [analytics, setAnalytics] = useState<Record<string, unknown> | null>(null); const [message, setMessage] = useState("");
  const [title, setTitle] = useState(""); const [body, setBody] = useState(""); const [startsAt, setStartsAt] = useState(""); const [extra, setExtra] = useState("");
  const endpoint = kind === "notifications" ? "campaigns" : kind === "clubs" ? "speaking-clubs" : kind;
  async function load() { const response = await fetch(`${apiBaseUrl}/admin/experience/${endpoint}`, { credentials: "include" }); if (!response.ok) return; const data = await response.json(); if (kind === "analytics") setAnalytics(data as Record<string, unknown>); else setItems(data as RecordItem[]); }
  useEffect(() => { void load(); }, [kind]);
  async function create(event: FormEvent) { event.preventDefault(); let payload: Record<string, unknown> = {}; if (kind === "notifications") payload = { title, body, channels: ["IN_APP", "EMAIL"], audience: { type: "ALL" }, publish: true, scheduledAt: startsAt || null, href: extra || "/dashboard" }; if (kind === "clubs") payload = { title, description: body, startsAt, capacity: Number(extra) || 16, durationMinutes: 45, levelCodes: ["A0", "A1", "A2", "B1", "B2", "C1"], materials: [] }; if (kind === "library") payload = { title, description: body, url: extra, type: "LINK", status: "PUBLISHED", levels: [], skills: [], tags: [] }; const response = await fetch(`${apiBaseUrl}/admin/experience/${endpoint}`, { method: "POST", credentials: "include", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); setMessage(response.ok ? "Сохранено и готово к публикации." : "Не удалось сохранить."); if (response.ok) { setTitle(""); setBody(""); setStartsAt(""); setExtra(""); await load(); } }
  if (kind === "analytics") return <div className="admin-experience"><header><span>Реальные события</span><h2>Аналитика платформы</h2></header><div className="analytics-metric-grid">{analytics ? Object.entries(analytics).filter(([, value]) => typeof value === "number").map(([key, value]) => <article key={key}><strong>{String(value)}</strong><span>{metricLabels[key] ?? key}</span></article>) : <p>Загружаем метрики…</p>}</div></div>;
  const copy = kind === "notifications" ? ["Кампании и уведомления", "Заголовок", "Текст сообщения", "Ссылка", "Дата отправки"] : kind === "clubs" ? ["Speaking clubs", "Название встречи", "Описание", "Количество мест", "Дата и время"] : ["Библиотека", "Название материала", "Описание", "Ссылка", ""];
  return <div className="admin-experience"><header><span>Управление контентом</span><h2>{copy[0]}</h2></header>{message ? <p className="inline-message">{message}</p> : null}<div className="admin-experience-layout"><form onSubmit={create}><label>{copy[1]}<input value={title} onChange={(event) => setTitle(event.target.value)} required /></label><label>{copy[2]}<textarea value={body} onChange={(event) => setBody(event.target.value)} required /></label><label>{copy[3]}<input value={extra} onChange={(event) => setExtra(event.target.value)} /></label>{copy[4] ? <label>{copy[4]}<input type="datetime-local" value={startsAt} onChange={(event) => setStartsAt(event.target.value)} required={kind === "clubs"} /></label> : null}<button>Сохранить</button></form><div className="admin-experience-list">{items.length ? items.map((item) => <article key={item.id}><span>{item.status ?? "готово"}</span><h3>{item.title}</h3>{item.startsAt ? <time>{new Intl.DateTimeFormat("ru", { dateStyle: "medium", timeStyle: "short" }).format(new Date(item.startsAt))}</time> : null}</article>) : <p>Записей пока нет.</p>}</div></div></div>;
}
